// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHrwLrmLwxWeAJmxTAD4X9vHFE56CM4bM',
    appId: '1:243742794624:web:b20535d6bf8b7b6f84d765',
    messagingSenderId: '243742794624',
    projectId: 'insta-clone-srikanta',
    authDomain: 'insta-clone-srikanta.firebaseapp.com',
    storageBucket: 'insta-clone-srikanta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsZSz5659avVNB1LNCax5mLJ5fMPwXiVw',
    appId: '1:243742794624:android:0bf3881b5e4efc6784d765',
    messagingSenderId: '243742794624',
    projectId: 'insta-clone-srikanta',
    storageBucket: 'insta-clone-srikanta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyJxlPEpdu6GHtqLp5IEwTLvS8mFoMIw',
    appId: '1:243742794624:ios:053326d5b6c7498a84d765',
    messagingSenderId: '243742794624',
    projectId: 'insta-clone-srikanta',
    storageBucket: 'insta-clone-srikanta.appspot.com',
    iosBundleId: 'com.example.riverPodCourse2x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPyJxlPEpdu6GHtqLp5IEwTLvS8mFoMIw',
    appId: '1:243742794624:ios:bffc82dc8171559384d765',
    messagingSenderId: '243742794624',
    projectId: 'insta-clone-srikanta',
    storageBucket: 'insta-clone-srikanta.appspot.com',
    iosBundleId: 'com.example.riverPodCourse2x.RunnerTests',
  );
}
